/**
 * Writes the numbered database/NN_*.sql files (paste into the Supabase SQL
 * editor in order) from the same sources the server uses: schema.ts and
 * seedData.ts. Run from the repo root: npm run db:sql
 * 13_useful_queries.sql is hand-written and left alone.
 */
import { mkdirSync, rmSync, writeFileSync } from 'node:fs';
import { initialServerState } from '../../src/services/serverCore';
import { SCHEMA_SECTIONS } from './schema';

const DAY = 24 * 60 * 60 * 1000;
const lit = (v: unknown) => `'${JSON.stringify(v).replace(/'/g, "''")}'::jsonb`;

const now = Date.now();
const state = initialServerState(now);

const recyclers = state.recyclers
  .map((r) => `  ('${r.recyclerId}', ${lit(r)})`)
  .join(',\n');

// Price dates are written relative to now() so the 60-day trend stays current
// whenever the seed is run.
const prices = state.prices
  .map((p) => {
    const daysAgo = Math.round((now - p.date) / DAY);
    const dated = `jsonb_set(${lit(p)}, '{date}', to_jsonb(floor(extract(epoch from now() - interval '${daysAgo} days') * 1000)))`;
    return `  (${dated})`;
  })
  .join(',\n');

const header = (file: string, title: string, note: string) =>
  `-- ============================================================================
-- ${file} — ${title}
-- ${note}
-- Generated by \`npm run db:sql\` — edit backend/src/schema.ts or src/data/seedData.ts, not this file.
-- ============================================================================
`;

const seedRecyclersSql = `${header('11_seed_recyclers.sql', 'Seed: recyclers', 'Fictional Nagpur facilities for the demo. Safe to re-run (existing rows kept).')}
insert into kc_recyclers (recycler_id, data) values
${recyclers}
on conflict (recycler_id) do nothing;
`;

const seedPricesSql = `${header('12_seed_prices.sql', 'Seed: 60-day price history', 'Only inserts into an EMPTY kc_prices: dates are relative to now(), so a re-run on another day would add a second history.')}
insert into kc_prices (price_key, data)
select md5(d::text), d from (values
${prices}
) as v(d)
where not exists (select 1 from kc_prices)
on conflict (price_key) do nothing;
`;

mkdirSync('database', { recursive: true });
rmSync('database/schema.sql', { force: true }); // superseded by the numbered files
rmSync('database/seed.sql', { force: true });
for (const section of SCHEMA_SECTIONS) {
  const note = section.supabaseOnly
    ? 'Supabase only (uses auth.users). Run first. The API server does not need it.'
    : 'Idempotent. The API server also applies this automatically on boot.';
  writeFileSync(`database/${section.file}`, header(section.file, section.title, note) + section.sql);
}
writeFileSync('database/11_seed_recyclers.sql', seedRecyclersSql);
writeFileSync('database/12_seed_prices.sql', seedPricesSql);
console.log(`wrote ${SCHEMA_SECTIONS.length + 2} files to database/`);
