-- ============================================================================
-- 01_users.sql — Users / profiles (Supabase Auth)
-- Supabase only (uses auth.users). Run first. The API server does not need it.
-- Generated by `npm run db:sql` — edit backend/src/schema.ts or src/data/seedData.ts, not this file.
-- ============================================================================

-- User profiles for Supabase Auth (e.g. Google sign-in).
-- One row per signed-in person; the role decides which side of the app they
-- see. Kept minimal on purpose (problem statement: avoid unnecessary personal
-- information) — no phone, no address, no name required.
create table if not exists public.kc_profiles (
  id                 uuid primary key references auth.users (id) on delete cascade,
  role               text not null default 'collector' check (role in ('collector', 'recycler', 'admin')),
  preferred_language text not null default 'hi' check (preferred_language in ('en', 'hi', 'mr')),
  operating_location text,
  collector_id       text unique,  -- the app's device-generated collector ID, once linked
  recycler_id        text,         -- kc_recyclers.recycler_id when role = 'recycler'
  recycler_verified  boolean not null default false,  -- set by an admin, never by the user
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now()
);

alter table public.kc_profiles enable row level security;

-- A signed-in user can read and edit only their own row, and can only pick
-- collector/recycler for themselves (admin is granted from the dashboard).
drop policy if exists "kc_profiles: read own" on public.kc_profiles;
create policy "kc_profiles: read own" on public.kc_profiles
  for select to authenticated using ((select auth.uid()) = id);

drop policy if exists "kc_profiles: update own" on public.kc_profiles;
create policy "kc_profiles: update own" on public.kc_profiles
  for update to authenticated
  using ((select auth.uid()) = id)
  with check ((select auth.uid()) = id and role in ('collector', 'recycler'));

-- Users may change only these columns; recycler_verified stays admin-only.
revoke update on public.kc_profiles from authenticated;
grant update (role, preferred_language, operating_location, collector_id, recycler_id)
  on public.kc_profiles to authenticated;

-- Create the profile automatically when someone signs up.
create or replace function public.kc_handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $fn$
begin
  insert into public.kc_profiles (id) values (new.id) on conflict (id) do nothing;
  return new;
end;
$fn$;

drop trigger if exists kc_on_auth_user_created on auth.users;
create trigger kc_on_auth_user_created
  after insert on auth.users
  for each row execute function public.kc_handle_new_user();

create or replace function public.kc_touch_updated_at()
returns trigger language plpgsql set search_path = '' as $fn$
begin
  new.updated_at = now();
  return new;
end;
$fn$;

drop trigger if exists kc_profiles_touch on public.kc_profiles;
create trigger kc_profiles_touch
  before update on public.kc_profiles
  for each row execute function public.kc_touch_updated_at();
