-- ============================================================================
-- 02_helpers.sql — Helper functions
-- Idempotent. The API server also applies this automatically on boot.
-- Generated by `npm run db:sql` — edit backend/src/schema.ts or src/data/seedData.ts, not this file.
-- ============================================================================

-- Epoch milliseconds (as the app stores time) -> timestamptz. IMMUTABLE so it
-- can be used in generated columns.
create or replace function kc_ms(v jsonb) returns timestamptz
language sql immutable as $fn$ select to_timestamp((v #>> '{}')::double precision / 1000) $fn$;
