-- ============================================================================
-- 03_recyclers.sql — Recycler / aggregator dataset
-- Idempotent. The API server also applies this automatically on boot.
-- Generated by `npm run db:sql` — edit backend/src/schema.ts or src/data/seedData.ts, not this file.
-- ============================================================================

-- Recycler / aggregator dataset
create table if not exists kc_recyclers (
  recycler_id          text primary key,
  data                 jsonb not null,
  name                 text    generated always as (data->>'name') stored,
  authorization_status text    generated always as (data->>'authorizationStatus') stored,
  authorization_id     text    generated always as (data->>'authorizationId') stored,
  address              text    generated always as (data#>>'{location,address}') stored,
  lat                  double precision generated always as ((data#>>'{location,lat}')::double precision) stored,
  lng                  double precision generated always as ((data#>>'{location,lng}')::double precision) stored,
  pickup_available     boolean generated always as ((data->>'pickupAvailable')::boolean) stored,
  service_area         text    generated always as (data->>'serviceArea') stored,
  contact              text    generated always as (data->>'contact') stored,
  updated_at           timestamptz not null default now()
);
