-- ============================================================================
-- 04_prices.sql — Price dataset
-- Idempotent. The API server also applies this automatically on boot.
-- Generated by `npm run db:sql` — edit backend/src/schema.ts or src/data/seedData.ts, not this file.
-- ============================================================================

-- Price dataset (market observations + recycler quotes + completed sales)
create table if not exists kc_prices (
  price_key        text primary key,            -- md5 of the row; rows are append-only
  data             jsonb not null,
  category         text    generated always as (data->>'category') stored,
  sub_category     text    generated always as (data->>'subCategory') stored,
  location         text    generated always as (data->>'location') stored,
  observed_at      timestamptz generated always as (kc_ms(data->'date')) stored,
  buying_price     numeric generated always as ((data->>'buyingPrice')::numeric) stored,
  quoted_price     numeric generated always as ((data->>'quotedPrice')::numeric) stored,
  unit             text    generated always as (data->>'unit') stored,
  recycler_id      text    generated always as (data->>'recyclerId') stored,
  market_range_low  numeric generated always as ((data->>'marketRangeLow')::numeric) stored,
  market_range_high numeric generated always as ((data->>'marketRangeHigh')::numeric) stored
);
create index if not exists kc_prices_category_time on kc_prices (category, observed_at);
