-- ============================================================================
-- 05_materials.sql — Material dataset (lots)
-- Idempotent. The API server also applies this automatically on boot.
-- Generated by `npm run db:sql` — edit backend/src/schema.ts or src/data/seedData.ts, not this file.
-- ============================================================================

-- Material dataset (one row per collected lot)
create table if not exists kc_lots (
  lot_id          text primary key,
  data            jsonb not null,
  collector_id    text    generated always as (data->>'collectorId') stored,
  category        text    generated always as (data->>'category') stored,
  sub_category    text    generated always as (data->>'subCategory') stored,
  description     text    generated always as (data->>'description') stored,
  condition       text    generated always as (data->>'condition') stored,
  source_type     text    generated always as (data->>'sourceType') stored,
  weight_kg       numeric generated always as ((data->>'approxWeightKg')::numeric) stored,
  estimated_value numeric generated always as ((data->>'estimatedValue')::numeric) stored,
  status          text    generated always as (data->>'status') stored,
  created_at      timestamptz generated always as (kc_ms(data->'createdAt')) stored,
  lat             double precision generated always as ((data#>>'{location,lat}')::double precision) stored,
  lng             double precision generated always as ((data#>>'{location,lng}')::double precision) stored,
  updated_at      timestamptz not null default now()
);
create index if not exists kc_lots_collector on kc_lots (collector_id);

-- Image-classifier suggestion next to the collector's chosen category: a
-- growing labelled dataset (photo thumbnail + human label + model guess).
alter table kc_lots add column if not exists ai_label text
  generated always as (data#>>'{aiSuggestion,label}') stored;
alter table kc_lots add column if not exists ai_confidence numeric
  generated always as ((data#>>'{aiSuggestion,confidence}')::numeric) stored;
alter table kc_lots add column if not exists ai_model text
  generated always as (data#>>'{aiSuggestion,model}') stored;
