-- ============================================================================
-- 06_transactions.sql — Transaction dataset
-- Idempotent. The API server also applies this automatically on boot.
-- Generated by `npm run db:sql` — edit backend/src/schema.ts or src/data/seedData.ts, not this file.
-- ============================================================================

-- Transaction dataset
create table if not exists kc_transactions (
  transaction_id     text primary key,
  data               jsonb not null,
  lot_id             text    generated always as (data->>'lotId') stored,
  collector_id       text    generated always as (data->>'collectorId') stored,
  recycler_id        text    generated always as (data->>'recyclerId') stored,
  quoted_price       numeric generated always as ((data->>'quotedPrice')::numeric) stored,
  final_price        numeric generated always as ((data->>'finalPrice')::numeric) stored,
  payment_status     text    generated always as (data->>'paymentStatus') stored,
  transaction_status text    generated always as (data->>'transactionStatus') stored,
  occurred_at        timestamptz generated always as (kc_ms(data->'dateTime')) stored,
  collection_lat     double precision generated always as ((data#>>'{collectionLocation,lat}')::double precision) stored,
  collection_lng     double precision generated always as ((data#>>'{collectionLocation,lng}')::double precision) stored,
  handover_lat       double precision generated always as ((data#>>'{handoverLocation,lat}')::double precision) stored,
  handover_lng       double precision generated always as ((data#>>'{handoverLocation,lng}')::double precision) stored,
  updated_at         timestamptz not null default now()
);
create index if not exists kc_transactions_collector on kc_transactions (collector_id);
create index if not exists kc_transactions_recycler on kc_transactions (recycler_id);

-- Pickup lifecycle (requested -> accepted -> on_the_way -> arriving -> completed | declined).
-- Added with ALTER so databases created before pickups existed are upgraded in place.
alter table kc_transactions add column if not exists pickup_status text
  generated always as (data#>>'{pickup,status}') stored;
alter table kc_transactions add column if not exists pickup_requested_at timestamptz
  generated always as (kc_ms(data#>'{pickup,requestedAt}')) stored;
alter table kc_transactions add column if not exists pickup_updated_at timestamptz
  generated always as (kc_ms(data#>'{pickup,updatedAt}')) stored;
create index if not exists kc_transactions_pickup on kc_transactions (recycler_id, pickup_status);
