-- ============================================================================
-- 07_traceability.sql — Traceability dataset + recycler confirmations
-- Idempotent. The API server also applies this automatically on boot.
-- Generated by `npm run db:sql` — edit backend/src/schema.ts or src/data/seedData.ts, not this file.
-- ============================================================================

-- Traceability dataset (verifiable handover records)
create table if not exists kc_traceability (
  handover_reference   text primary key,         -- KC-XXXXXX
  data                 jsonb not null,           -- includes photoThumbnails (small data URLs)
  lot_id               text    generated always as (data->>'lotId') stored,
  transaction_id       text    generated always as (data->>'transactionId') stored,
  collector_id         text    generated always as (data->>'collectorId') stored,
  recycler_id          text    generated always as (data->>'recyclerId') stored,
  handover_hash        text    generated always as (data->>'handoverHash') stored,
  weight_kg            numeric generated always as ((data->>'weight')::numeric) stored,
  recorded_at          timestamptz generated always as (kc_ms(data->'timestamp')) stored,
  lat                  double precision generated always as ((data#>>'{location,lat}')::double precision) stored,
  lng                  double precision generated always as ((data#>>'{location,lng}')::double precision) stored,
  location_approximate boolean generated always as (coalesce((data->>'locationApproximate')::boolean, false)) stored,
  status               text    generated always as (data->>'status') stored,
  confirmed_by         text    generated always as (data#>>'{recyclerConfirmation,confirmedBy}') stored,
  confirmed_at         timestamptz generated always as (kc_ms(data#>'{recyclerConfirmation,confirmedAt}')) stored,
  updated_at           timestamptz not null default now()
);

-- Recycler confirmations (may arrive before the handover record syncs)
create table if not exists kc_confirmations (
  handover_reference text primary key,
  data               jsonb not null,
  confirmed_by       text    generated always as (data->>'confirmedBy') stored,
  confirmed_at       timestamptz generated always as (kc_ms(data->'confirmedAt')) stored,
  final_price        numeric generated always as ((data->>'finalPrice')::numeric) stored,
  payment_status     text    generated always as (data->>'paymentStatus') stored
);
