-- ============================================================================
-- 08_flags_audit.sql — Anomaly flags + audit trail
-- Idempotent. The API server also applies this automatically on boot.
-- Generated by `npm run db:sql` — edit backend/src/schema.ts or src/data/seedData.ts, not this file.
-- ============================================================================

-- Abnormal transaction flags (anomaly detection output)
create table if not exists kc_flags (
  transaction_id text primary key,
  data           jsonb not null,
  reason         text    generated always as (data->>'reason') stored,
  deviation_pct  numeric generated always as ((data->>'deviationPct')::numeric) stored,
  flagged_at     timestamptz generated always as (kc_ms(data->'at')) stored
);

-- Audit trail of every accepted write
create table if not exists kc_audit (
  seq  bigint primary key,
  data jsonb not null,
  kind text generated always as (data->>'kind') stored,
  ref  text generated always as (data->>'ref') stored,
  at   timestamptz generated always as (kc_ms(data->'at')) stored
);
