-- ============================================================================
-- 09_collectors.sql — Collector dataset (view)
-- Idempotent. The API server also applies this automatically on boot.
-- Generated by `npm run db:sql` — edit backend/src/schema.ts or src/data/seedData.ts, not this file.
-- ============================================================================

-- Collector dataset: minimal by design (pseudonymous device ID, no name/phone).
create or replace view kc_collectors as
select l.collector_id,
       count(distinct l.lot_id)                                                   as lots,
       count(distinct t.transaction_id)                                           as transactions,
       coalesce(sum(coalesce(t.final_price, t.quoted_price))
                filter (where t.payment_status <> 'pending'), 0)                  as earnings_settled,
       coalesce(sum(coalesce(t.final_price, t.quoted_price))
                filter (where t.payment_status = 'pending'
                          and t.transaction_status <> 'pending'), 0)              as dues_pending,
       min(l.created_at)                                                          as first_seen,
       max(l.created_at)                                                          as last_seen
from kc_lots l
left join kc_transactions t on t.lot_id = l.lot_id
group by l.collector_id;
