-- ============================================================================
-- 10_security.sql — Row Level Security
-- Idempotent. The API server also applies this automatically on boot.
-- Generated by `npm run db:sql` — edit backend/src/schema.ts or src/data/seedData.ts, not this file.
-- ============================================================================

-- Supabase exposes the public schema over its REST API. Row Level Security
-- with no policies blocks that path entirely; the app server connects as the
-- database owner and is unaffected.
alter table kc_recyclers     enable row level security;
alter table kc_prices        enable row level security;
alter table kc_lots          enable row level security;
alter table kc_transactions  enable row level security;
alter table kc_traceability  enable row level security;
alter table kc_confirmations enable row level security;
alter table kc_flags         enable row level security;
alter table kc_audit         enable row level security;
